CREATE TABLE IF NOT EXISTS BRANDS (
  BRAND_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS PRICES (
  BRAND_ID INTEGER NOT NULL,
  PRICE_LIST INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DECIMAL(20,2) NOT NULL,
  CURRENCY VARCHAR(3) NOT NULL,
  PRIMARY KEY (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE, PRIORITY),
  CONSTRAINT brand_id_brand_fk
    FOREIGN KEY (BRAND_ID)
    REFERENCES BRANDS (BRAND_ID));